config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :pages, only: %i[index]
  resources :projects, only: %i[show new create destroy update edit]


  root to: "pages#home"

  resources :projects, only: %i[show] do
    # Afficher /project/1/levels/1
    resources :levels, only: %i[show] do
      # Afficher /project/1/levels/1/attempts
      namespace :game do
        resources :projects, only: %i[edit update show]
      end
      resources :attempts, only: %i[index create]
      # # Afficher /project/1/level/1/project/1 -> flou, ticket à réaliser
      # namespace :game do
      #   resources :projects, only %i[show update create]
      # end
    end
  end

  resources :startups, only: %i[index show] do
    resources :favorites, only: %i[create new index]
  end

  get 'pages/win', to: 'pages#win', as: :win_page
  get 'pages/phone', to: 'pages#phone', as: :phone_page

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attempt.rb
class Attempt < ApplicationRecord
  belongs_to :level
  belongs_to :project

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :project
  belongs_to :startup
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :attempts, dependent: :destroy
  has_one_attached :photo

  def self.max_level_reached(project_id)
    max_level = joins(:attempts)
      .where('attempts.project_id = ? AND attempts.result = ?', project_id, true)
      .maximum(:index)

    max_level || 0
  end

  rails_admin do
    edit do
      field :description do
        render do
          bindings[:view].render :partial => "bootsy_news_content_field", :locals => {:field => self, :form => bindings[:form]}
        end
      end
    end
    show do
      field :content do
        formatted_value do
          value.html_safe
        end
      end
    end
  end

  def win?(params)
    params[:level][:funds].to_i >= self.min_funds && params[:level][:employees].to_i >= self.min_employees
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :attempts, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true

end

app/models/startup.rb
class Startup < ApplicationRecord
  has_many :favorites, dependent: :destroy
  # has_one_attached :logo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_project, :set_startup, only: %i[create new]
  def index
    @favorites = Favorite.all
  end

  def new
    @favorite = Favorite.new
  end

  def create
    #@favorite = @project.favorites.new(startup: @startup)
    @favorite = Favorite.new
    @favorite.project = current_user.projects.last
    @favorite.startup = @startup
    if @favorite.save

      redirect_to project_path(@project)
    else

      render :new, status: :unprocessable_entity
      puts "Erreur lors de l'enregistrement du favori : #{favorite.errors.full_messages.join(', ')}"
    end
  end

  private

  def set_project
    @project = current_user.projects.last
  end

  def set_startup
    @startup = Startup.find(params[:startup_id])
  end
end

app/controllers/game/projects_controller.rb
class Game::ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update]
  # before_action :set_level, only: [:edit]

  def show
    @max_level_reached = Level.max_level_reached(@project)
    @attempt = @project.attempts.last
    @level = Level.find_by(index: Level.max_level_reached(@project) + 1) || Level.find_by(index: Level.max_level_reached(@project))
    @next_level = Level.find_by(index: @max_level_reached + 1)
    @project.attempts.destroy_all unless @next_level.present?
    @failed_startups = []
    @failed_startups = Startup.all.sample(2)
  end

  def edit
    @max_level_reached = Level.max_level_reached(@project)
    @level = Level.find_by(index: Level.max_level_reached(@project) + 1) || Level.find_by(index: Level.max_level_reached(@project))
  end

  def update
    @level = Level.find(params[:id])

    if @level.win?(params)
      @attempt = Attempt.create(result: true)
      @project.funds = params[:level][:funds]
      @project.employees = params[:level][:employees]
      @project.save

    else
      @attempt = Attempt.create(result: false)
    end

    @attempt.project = @project
    @attempt.level = @level
    @attempt.save

    redirect_to project_level_game_project_path(@project, @level)
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  # def set_level
  #   @level = Project.find(params[:id])
  # end

  def project_params
    # Pour le moment, tous les paramètres sont autorisés, voir Jonathan
    params.require(:project).permit!
  end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController

  def show
    @project = Project.find(params[:project_id])
    # Comment afficher niveau max ?
    @level = Level.find_by(index: Level.max_level_reached(@project) + 1) || Level.find_by(index: Level.max_level_reached(@project))
    @attempt_count = @project.attempts.where(result: false).count
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :phone_page]
  before_action :redirect_mobile_users, only: [:phone_page]

  def home
  end

  def index
  end

  def show
  end

  def win
  end

  def phone_page
  end

  private

  def redirect_mobile_users

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:destroy]


  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save
      redirect_to project_path(@project), notice: "Nouvelle partie créée avec succès."
    else
      render :new, status: :unprocessable_entity
      puts "Erreur lors de l'enregistrement du projet : #{@project.errors.full_messages.join(', ')}"
    end
  end

  def show
    @project = Project.find(params[:id])
    @favorites = @project.favorites
    @max_level_reached = Level.max_level_reached(@project)

    # Trouver le niveau suivant s'il existe, sinon utiliser le niveau actuel
    @next_level = Level.find_by(index: @max_level_reached + 1) || Level.find_by(index: @max_level_reached)
  end



  def destroy
    @project.destroy
    redirect_to new_project_path
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :sector, :localisation, :employees, :funds, :avatar)
  end

end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  def index
    @startups = Startup.all.shuffle

    if params[:query].present?
      sql_subquery = <<~SQL
        startups.name ILIKE :query
        OR startups.founder ILIKE :query
        OR startups.localisation ILIKE :query
        OR startups.sector ILIKE :query
        OR startups.fail_reason ILIKE :query
      SQL
      @startups = Startup.all.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def show
    @startup = Startup.find(params[:id])
    @favorite = Favorite.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/game/projects/_card_you_lose.html.erb
<div class="you-win-card">
  <div class="text-center">
      <p class="red-level">DEFAITE</p>
    </div>
</div>

app/views/game/projects/_card_you_win.html.erb
<div class="you-win-card">
  <div class="text-center">
      <p class="green-level">VICTOIRE</p>
    </div>
</div>

app/views/game/projects/show.html.erb
<div class="all-game">
  <div class="mx-5">
    <div class="d-flex justify-content-center">

      <div class="grave-card align-self-center col-6">
        <div class="card-gray p-2">
          <% if @attempt.result == true %>
            <%= render partial: "card_you_win", locals: {level: @level} %>
          <% elsif @attempt.result == false %>
            <%= render partial: "card_you_lose", locals: {level: @level} %>
          <% end %>
        </div>
      </div>

      <div class="container mt-3">
        <div class="row justify-content-center">
          <div class="infos-card col-12 d-flex justify-content-around p-5">
            <div class="game-card" style="width: 40rem;">
              <div class="card-body d-flex flex-column align-items-center gap-1">
                <h1 class="game-card-title text-center"><b>Statistiques</b></h3>


                <h6 class="game-card-title">- Ma progression -</h6>
                <p class="card-text">Capital du projet : <%= @project.funds.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\1 ').reverse %> €</p>

                <p class="card-text mb-0"><strong>Ces startups ont échoué à ce stade :</strong></p>

                <div class="project-wrapper-game d-flex gap-5 p-1 justify-content-around" >
                 <% @failed_startups.each do |startup| %>
                 <div class="project-wrapper-mini mb-2">
                    <%= render partial: "startups/startup_card", locals: {startup: startup} %>
                 </div>
                <% end %>
                </div>

                 <% if @attempt.result == true %>
                  <h6 class="game-card-title">- Niveau <%= @level.index %> : Prochains objectifs -</h6>
                <% else %>
                  <h6 class="game-card-title">Niveau <%= @level.index %> - Objectifs du niveau :</h6>
                <% end %>

                <p class="card-text">Capital minimum : <%= @level.min_funds.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\1 ').reverse %> €</p>
                <p class="card-text">Nombre d'employé(s) minimum : <%= @level.min_employees %></p>
              </div>

                         <div class="d-flex justify-content-end">
                  <% if @attempt.result == false %>
                    <%= link_to 'Rejouer', edit_project_level_game_project_path(@project, @level), class: "button-dark" %>
                  <% elsif @next_level.present? && @attempt.result == true  %>
                    <%= link_to 'Continuer', project_level_path(@project, @next_level), class: "button-dark" %>
                  <% elsif !@next_level.present?  %>
                    <%= link_to 'Page finale', win_page_path, class: "button-dark" %>
                  <% end %>
                            </div>
                </div>
          </div>
        </div>
      </div>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StationFails</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="/path/to/font-awesome/css/font-awesome.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
     <%# <%= javascript_include_tag 'banner' %>
  </head>
  <body data-controller ="phone-page">
      <%= render "shared/navbar" %>
      <div id="page-container">
        <%= render "shared/flashes" %>
        <%= yield %>
      </div>
      <%= render "shared/footer" %>

  </body>
</html>

app/views/levels/show.html.erb
<div class="all-game">
  <div class="container mt-5">
    <div class="d-flex  ">
      <div class="grave-card col-4 align-self-center" >
        <div class="card-gray p-5  mt-2">
            <%= render partial: "level_card", locals: {level: @level} %>
        </div>
      </div>
      <div class="infos-card col-8 align-self-center p-5 mx-5 mt-2">
          <div class="d-flex justify-content-center">
          <div class="game-card" style="width: 40rem;">
            <div class="card-body">

             <h4 class="title-level">Niveau <%= @level.index %> </h4>
              <h3 class="title-level"><%= @level.name %> </h3>
             <div class="level-text">
               <p ><%= @level.description.html_safe %></p>
             </div>
               <div class="d-flex justify-content-center">
                <%= link_to "Play", edit_project_level_game_project_path(@project, @level), class: "btn-green-banner"  %>

               </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div  data-controller="home">
<div class="beta-banner">
<div class="beta-banner-shine">
  <h3>🎮 Station Fails v1.0 est disponible gratuitement en version bêta jusqu'au 12 décembre minuit ! Profites-en dès maintenant !</span> 🪦</h3>
</div>
</div>
<div class="banner-div">
  <%= render partial: "banner" %>
</div>

<div class="d-flex white-banner py-5">
  <div class="d-flex flex-grow-1 align-items-center">
    <div class="px-5">
      <h3 class="text-left"><strong>COMMENCE L'AVENTURE ENTREPRENEURIALE MAINTENANT</strong></h3>
      <h4 class="text-left mb-3">Plonge dans une aventure captivante aux graphismes époustouflants. <br>Profite dès maintenant de l'expérience de jeu rétro qui vous transporte dans un univers unique !</h4>
    </div>
    <div class="col-4 d-flex align-items-center" data-home-target="button">
      <% if user_signed_in? %>
        <% if current_user.projects.last %>
          <%= link_to "JOUER MAINTENANT", project_path(current_user.projects.last), class:"btn-blink-banner mx-3" %>
        <% else %>
          <%= link_to "JOUER MAINTENANT", new_project_path, class:"btn-blink-banner mx-3" %>
        <% end %>
      <% else %>
        <%= link_to "JOUER MAINTENANT", new_user_session_path, class:"btn-blink-banner mx-3" %>
      <% end %>
    </div>
  </div>
</div>

<div class="green-banner">
  <!-- Carte 1 -->
  <div class="info-card">
    <h1>90%</h1>
    <p>Taux d'échec des startups</p>
    <p class="explanation">Environ 90% des startups échouent au cours de leurs premières années, mettant en lumière les défis du démarrage d'une nouvelle entreprise.</p>
    <img src="https://raw.githubusercontent.com/gwittebolle/station_fails/master/app/assets/images/worm.png" alt="Worm Image" class="hover-image">
  </div>

  <!-- Carte 2 -->
  <div class="info-card">
    <h1>Technologie</h1>
    <p>Secteur le plus touché</p>
    <p class="explanation">La technologie est le secteur où les startups connaissent le plus d'échecs, malgré son potentiel innovant.</p>
    <img src="https://raw.githubusercontent.com/gwittebolle/station_fails/master/app/assets/images/worm.png" alt="Worm Image" class="hover-image">
  </div>

  <!-- Carte 3 -->
  <div class="info-card">
    <h1>2 ans</h1>
    <p>Durée de vie moyenne</p>
    <p class="explanation">En moyenne, les startups survivent pendant environ 2 ans avant de faire face à des défis insurmontables, soulignant la nécessité d'une croissance rapide.</p>
    <img src="https://raw.githubusercontent.com/gwittebolle/station_fails/master/app/assets/images/worm.png" alt="Worm Image" class="hover-image">
  </div>
</div>









<div class="d-flex p-3 m-3 align-items-start">
<div class="col-9 d-flex flex-column">
<div>
  <div class="container mt-4">
    <div class="container mt-4">
      <div class="">
        <h3 class="p-1 text-white text-left ml-5">CHRONIQUES DU REPOS ETERNEL </h3>
      </div>
      <hr class="p-0 m-0 ligne">
          <div class="article">
            <ul class="article-list">
              <li><a
                  href="https://www.usinenouvelle.com/editorial/face-aux-difficultes-de-financement-les-start-up-reclament-davantage-de-commandes-privees-et-publiques.N2170247" target="_blank">- Face
                  aux difficultés de financement, les start-up réclament davantage de commandes privées et publiques</a>
              </li>
              <li><a
                  href="https://business-cool.com/actualites/actu-business/startup-kikikickz-liquidation-judiciaire/" target="_blank">- La
                  startup Kikikickz placée en liquidation judiciaire</a></li>
              <li><a href="https://www.frenchweb.fr/fin-du-dreem-pour-de-nombreuses-startups/443589" target="_blank">- Fin du DREEM pour
                  de nombreuses startups.</a></li>
              <li><a href="https://www.maddyness.com/2023/10/27/luko-rachat-liquidation/" target="_blank">- Luko au bord du gouffre :
                  comment la startup en est arrivée là</a></li>
                   <li><a href="https://www.maddyness.com/2022/10/28/liquidation-next-station/" target="_blank">- La liquidation de Next
                  Station racontée par un de ses cofondateurs</a></li>
              <li><a href="https://www.frenchweb.fr/jai-22-ans-et-jai-plante-ma-premiere-start-up/302083" target="_blank">- J’ai 22 ans et
                  j’ai planté ma première start-up</a></li>
            </ul>
          </div>
    </div>
<div class="container mt-4">
      <div class=" ">
        <h3 class="p-1 text-white text-left ml-5">CHAMBRE FUNERAIRE DES CRITIQUES </h3>
      </div>
  <hr class="p-0 m-0 ligne mb-3">
  <div class="row d-flex">
      <div class="col-md-4">
        <div class="review text-white">
          <h5>JeuxMasters</h5>
          <p class="comment">Station Fails offre une expérience de jeu captivante avec des graphismes époustouflants. La narration immersive et les mécaniques de jeu innovantes en font un incontournable pour les amateurs de jeux d'aventure. Un joyau du rétro gaming!"</p>
          <p class="rating">8.9/10</p>
        </div>
      </div>

      <div class="col-md-4 text-white">
        <div class="review">
          <h5>Joystick Fantastique</h5>
          <p class="comment">"Station Fails est une perle rare dans l'industrie du jeu. Les concepteurs ont réussi à créer un monde fantastique avec des énigmes stimulantes. Les graphismes sont à couper le souffle, et la bande-son ajoute une dimension supplémentaire à l'expérience. Une ode aux classiques du jeu vidéo!"</p>
          <p class="rating">9.5/10</p>
        </div>
      </div>

      <div class="col-md-4 text-white">
        <div class="review">
          <h5>GamingMagique</h5>
          <p class="comment">"Station Fails brille par son originalité et son gameplay captivant. Les personnages bien développés et l'intrigue immersive en font un jeu exceptionnel. Les joueurs seront absorbés par l'univers riche et les défis stimulants. Une expérience rétro qui mérite d'être vécue!"</p>
          <p class="rating">9.2/10</p>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

</div>
<div class="d-flex sidebar-column col-3 flex-column">
  <div class="col-12 shadow-sm m-3 d-flex justify-content-evenly border-bottom">
    <div class="mx-2 col-3 d-flex align-items-center flex-column justify-content-center">
      <h3 class="text-center p-1 text-white mt-2">DERNIER ENTERREMENT</h3>
      <div class="d-flex flex-column align-items-center">

            <div class="project-wrapper-mini mb-4">
                <%= render partial: "startups/startup_card", locals: {startup: Startup.last} %>
            </div>
              <%= link_to "VISITER LE CIMETIERE", startups_path, class:"btn-special-gray-lg mx-3 mb-5" %>

            </div>
        </div>
  </div>
  <div class="col-12 shadow-sm m-3 d-flex justify-content-evenly">
    <div class="mx-2 col-12 d-flex align-items-center flex-column">
          <h3 class="text-white my-3">PARIE SUR LE PROCHAIN DEFUNT !</h3>
          <div class="col-8 d-flex justify-content-between align-items-center">
            <div class="d-flex flex-column align-items-center">
              <h6 class="text-white">Wakely</h6>
              <h3 class="text-white">1.96</h3>
            </div>
            <div><h3 class="text-white">OU</h3></div>
            <div class="d-flex flex-column align-items-center">
              <h6 class="text-white">Astreinte</h6>
              <h3 class="text-white">1.92</h3>
            </div>
          </div>
          <p class="text-white"><i>Cotes fournies par Betfriends</i></p>
        </div>
  </div>
</div>
</div>

<div class="col-12 newsletter-subscribe p-0 pb-5 mx-0 my-2 d-flex flex-column text-start">
  <div>
    <h4 class="text-white mx-5">La nécrologie des startups dans tes mails chaque dernier vendredi du mois ! </h4>
  </div>
  <div>
    <form action="<%= new_user_session_path %>" method="get" class="mx-5 d-flex justify-content-start  ">
      <input type="email" name="email" placeholder="Votre adresse e-mail" required />
      <button type="submit" class="btn-special-gray">S'abonner</button>
    </form>
  </div>
</div>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light" data-phone-page-target="navbar">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand p-0 m-0" do %>
      <%= image_tag("logo-station-fails.png", width: 350, class: "img-fluid") %>
    <% end %>



    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

        <div class="d-flex justify-content-betnween align-items-center">

          <li class="nav-item mx-2">
            <% if current_user.projects.last %>
              <%= link_to "Le Jeu", project_path(current_user.projects.last), class:"nav-link" %>

            <% else %>
              <%= link_to "Le Jeu", new_project_path, class:"nav-link" %>


            <% end %>

              <li class="nav-item active mx-2">
            <%= link_to "Cimetière", startups_path, class:"nav-link" %>
          </li>

          </li>
          <li class="nav-item dropdown mx-2">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.avatar.attached? %>
              <%= cl_image_tag(current_user.avatar.key, class: "avatar", gravity: "face", crop: "fill") %>
            <% else %>
              <%= image_tag("default_picture.jpeg", class: "avatar", alt: "dropdown menu") %>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Editer mon profil", edit_user_registration_path, class: "dropdown-item bg-light" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item bg-light" %>
            </div>
          </li>
        </div>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_project_card.html.erb
<div class="project-card">


  <div class="container-title flex-column">

    <div class="actu-level mt-5">
      <% if @next_level.index == 1 %>
          <h1 class="green-level"> LEVEL <%=  @next_level.index %></h1>
      <% elsif @next_level.index == 2 %>
          <h1 class="blue-level"> LEVEL <%=  @next_level.index %></h1>
      <% elsif @next_level.index == 3 %>
          <h1 class="red-level"> LEVEL <%=  @next_level.index %></h1>
      <% elsif @next_level.index == 4 %>
          <h1 class="purple-level"> LEVEL <%=  @next_level.index %></h1>
        <% end %>
      </div>


<div class="col-12 d-flex justify-content-center">
    <div class="card card-progress bg-white text-center mt-5 mb-5">
      <h3 class="card-header"><b><%= @project.name %> - MES STATS</b></h3>
      <div class="card-body">
        <div class="d-flex justify-content-between">
          <div class="d-flex justify-content-center">
          <h5 class="text-center">MES STATS</h5>
          </div>
           <div class="money-box p-3  ">

            <% if @project.funds <= 1000 %>
                <p class=""><%= @project.funds %></p>
                <h1 class="text-center">€</h1>
              <% elsif @project.funds <= 10000 %>
                <p class=""><%= @project.funds / 1000 %>K </p>
                <h1 class="text-center">€</h1><!-- Affiche les premiers chiffres + 'K' -->
              <% elsif @project.funds <= 100000 %>
                <p class=""><%= @project.funds / 1000 %>K </p>
                <h1 class="text-center">€</h1><!-- Affiche les premiers chiffres + 'K' -->
              <% else %>
                <p class=""><%= @project.funds / 1_000_000 %>M </p>
                <h1 class="text-center">€</h1><!-- Affiche les premiers chiffres + 'M' pour 1 million et plus -->
              <% end %>



      </div>

      <div class="money-box p-2">
        <% if @project.employees <= 1  %>
          <p class=""><%= @project.employees %></p>
          <h1 class="text-center"> EMPLOYE</h1>
        <% else %>
          <p class=""><%= @project.employees %></p>
          <h1 class="text-center"> EMPLOYES</h1>
        <% end %>
      </div>
        </div>
      </div>
    </div>
  </div>



    <div class="play">
      <% if @project.attempts.count > 0 %>
      <%= link_to 'REPRENDRE', project_level_path(@project, @next_level), class: "btn-green-banner btn-play mx-3" %>

      <% else %>
      <%= link_to 'JOUER', project_level_path(@project, @next_level), class: "btn-green-banner btn-play mx-3" %>
      <% end %>
    </div>
  </div>



  <div class="box-title mt-5 mb-3">
       <hr class="my-line mb-3">
      <h2 class="text-gray text-center">  </h2>
      <ul class="list-item">
        <li class="card-text text-center"><em> - <%= @project.description.capitalize|| 'N/A' %> -</em></li>
        <li class="card-text text-center"><span class="text-gray"> <%= @project.localisation.capitalize || 'N/A' %> -
            <%= @project.sector.capitalize || 'N/A' %> </span></li>
      </ul>
    </div>

 <% if @favorites.present? %>

  <div class="col-12 d-flex justify-content-center">
    <div class="card card-favorites bg-white text-center mt-5 mb-5">
      <h5 class="card-header">Mes favoris</h5>
      <div class="card-body">
        <div class="d-flex justify-content-between">
          <% @favorites.each do |favorite| %>
          <div class="project-wrapper-mini ">
            <%= render "startups/startup_card", startup: favorite.startup %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <% else %>
   <div class="d-flex justify-content-center p-4">

     <%= link_to "VISITER LE CIMETIERE", startups_path, class:"btn-green-banner mx-3 " %>
  </div>
  <% end %>
        <hr class="my-line mb-3 mt-3">
  <div class="d-flex justify-content-center p-4">
    <%= link_to "NOUVELLE PARTIE", project_path(@project), data: {turbo_method: :delete, turbo_confirm: "Une nouvelle partie écrasera la partie précédente. Confirme ton choix." }, class: 'btn-green-banner mx-3' %>
  </div>
</div>

app/views/startups/_startup_card.html.erb
  <div class="startup-card">
    <div class="text-center p-3">
    <%= link_to startup_path(startup) do %>
         <% if startup.logo.present?%>
        <img src="<%= startup.logo %>", class="logo">
        <% else %>
     <img src="https://cdn.dribbble.com/userupload/3499938/file/original-c6341bf029f595d84f1c3f3c99a32f81.jpg?resize=450x338&vertical=center", class="logo">
        <% end %>
     <% end  %>
     <div class=" d-flex flex-column">
       <div class="mt-1 mb-3 up-class">
          <h3 class="p-1 m-0"><b><%= startup.name %></b></h3>
          <h6 class="hide-year"><small><%= startup.birth_year %> - <%= startup.death_year %></small></h6>
       </div>
     </div>
   </div>
</div>